### ISSUE TITLE
Fix malformed XML error

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-metadata/metadata-remediation#45]
These objects were left open previously and are in a state where the MODS cannot be saved after it is corrected. Need to work with Andrew to resolve the situation and then move `type` and `displayLabel` from `title` to `titleInfo`.

druid:rd993xp4760
druid:sm238sx9481
druid:tr686ng1378
druid:xg349km5552

**Comment by cebraj** [comment]
Fixed! I also noticed in the subjects that the attribute lang="eng" was in the topic/geographic sub-elements instead of the higher-level subject element. I edited those, hope that was the right thing to do. I was just going by the modsulator template. Do I need to let Kim Durante know about these? Maybe she needs to adjust the xsl transformation?
